import { Component } from '@angular/core';

@Component({
  selector: 'app-adverts-form',
  templateUrl: './adverts-form.component.html',
  styleUrls: ['./adverts-form.component.scss'],
})
export class AdvertsFormComponent {
  data = [
    {
      description: 'عمليات در حال تداوم:',
      val1: '',
      val2: '',
      val3: '',
      val4: '',
      isImportant: false,
    },
    {
      description: 'درآمدهاي عملياتي',
      val1: '۲,۹۷۸,۸۵۲',
      val2: '۲,۷۶۱,۳۴۴',
      val3: '۱۳,۳۶۶,۷۴۱',
      val4: '۸',
      isImportant: false,
    },
    {
      description: 'بهاى تمام شده درآمدهاي عملياتي',
      val1: '(۲,۱۹۶,۰۱۰)',
      val2: '(۲,۱۴۷,۵۶۵)',
      val3: '(۱۰,۶۸۲,۶۹۲)',
      val4: '(۲)',
      isImportant: false,
    },
    {
      description: 'سود (زيان) ناخالص',
      val1: '۷۸۲,۸۴۲',
      val2: '۶۱۳,۷۷۹',
      val3: '۲,۶۸۴,۰۴۹',
      val4: '۲۸',
      isImportant: true,
    },
    {
      description: 'هزينه‏ هاى فروش، ادارى و عمومى',
      val1: '(۱۸۳,۱۱۱)',
      val2: '(۱۵۰,۳۵۱)',
      val3: '(۴۰۲,۸۵۲)',
      val4: '(۲۲)',
      isImportant: false,
    },
    {
      description: 'هزينه کاهش ارزش دريافتني‏ها (هزينه استثنايي)',
      val1: '۰',
      val2: '۰',
      val3: '۰',
      val4: '۰',
      isImportant: false,
    },
    {
      description: 'ساير درآمدها',
      val1: '۱۵۵,۱۳۲',
      val2: '۱۳۲,۲۹۸',
      val3: '۲۲۷,۸۶۷',
      val4: '۱۷',
      isImportant: false,
    },
    {
      description: 'ساير هزينه‌ها',
      val1: '۰',
      val2: '۰',
      val3: '۰',
      val4: '۰',
      isImportant: false,
    },
    {
      description: 'سود (زيان) عملياتى',
      val1: '۷۵۴,۸۶۳',
      val2: '۵۹۵,۷۲۶',
      val3: '۲,۵۰۹,۰۶۴',
      val4: '۲۷',
      isImportant: true,
    },
    {
      description: 'هزينه هاي مالي(غيرعملياتي)',
      val1: '۰',
      val2: '۰',
      val3: '۰',
      val4: '۰',
      isImportant: false,
    },
    {
      description:
        'ساير درآمدها و هزينه‏ هاى غيرعملياتى - درآمد سرمايه‌گذاري‌ها',
      val1: '۱۱۳,۶۸۹',
      val2: '۱,۸۰۳',
      val3: '۸,۷۷۳',
      val4: '۶,۲۰۶',
      isImportant: false,
    },
    {
      description: 'ساير درآمدها و هزينه‌هاي غيرعملياتي- اقلام متفرقه',
      val1: '۵,۰۷۳',
      val2: '۲۶۶,۷۶۰',
      val3: '۱۷۴,۱۶۱',
      val4: '(۹۸)',
      isImportant: false,
    },
    {
      description: 'سود (زيان) عمليات در حال تداوم قبل از ماليات',
      val1: '۸۷۳,۶۲۵',
      val2: '۸۶۴,۲۸۹',
      val3: '۲,۶۹۱,۹۹۸',
      val4: '۱',
      isImportant: true,
    },
    {
      description: 'هزينه ماليات بر درآمد:',
      val1: '',
      val2: '',
      val3: '',
      val4: '',
      isImportant: false,
    },
    {
      description: 'سال جاري',
      val1: '(۱۷۰,۷۳۳)',
      val2: '(۱۳۴,۸۹۳)',
      val3: '(۵۶۵,۸۹۲)',
      val4: '(۲۷)',
      isImportant: false,
    },
    {
      description: 'سال‌هاي قبل',
      val1: '۰',
      val2: '۰',
      val3: '۰',
      val4: '۰',
      isImportant: false,
    },
    {
      description: 'سود (زيان) خالص عمليات در حال تداوم',
      val1: '۷۰۲,۸۹۲',
      val2: '۷۲۹,۳۹۶',
      val3: '۲,۱۲۶,۱۰۶',
      val4: '(۴)',
      isImportant: true,
    },
    {
      description: 'عمليات متوقف شده:',
      val1: '',
      val2: '',
      val3: '',
      val4: '',
      isImportant: false,
    },
    {
      description: 'سود (زيان) خالص عمليات متوقف شده',
      val1: '۰',
      val2: '۰',
      val3: '۰',
      val4: '۰',
      isImportant: false,
    },
    {
      description: 'سود (زيان) خالص',
      val1: '۷۰۲,۸۹۲',
      val2: '۷۲۹,۳۹۶',
      val3: '۲,۱۲۶,۱۰۶',
      val4: '(۴)',
      isImportant: true,
    },
    {
      description: 'سود (زيان) پايه هر سهم:',
      val1: '',
      val2: '',
      val3: '',
      val4: '',
      isImportant: false,
    },
    {
      description: 'عملياتي (ريال)',
      val1: '۱۱۳',
      val2: '۱۴۴',
      val3: '۶۰۸',
      val4: '(۲۲)',
      isImportant: false,
    },
    {
      description: 'غيرعملياتي (ريال)',
      val1: '۲۲',
      val2: '۸۴',
      val3: '۵۶',
      val4: '(۷۴)',
      isImportant: false,
    },
    {
      description: 'ناشي از عمليات در حال تداوم',
      val1: '۱۳۵',
      val2: '۲۲۸',
      val3: '۶۶۴',
      val4: '(۴۱)',
      isImportant: true,
    },
    {
      description: 'ناشي از عمليات متوقف شده',
      val1: '۰',
      val2: '۰',
      val3: '۰',
      val4: '۰',
      isImportant: false,
    },
    {
      description: 'سود (زيان) پايه هر سهم',
      val1: '۱۳۵',
      val2: '۲۲۸',
      val3: '۶۶۴',
      val4: '(۴۱)',
      isImportant: true,
    },
    {
      description: 'سود (زيان) خالص هر سهم– ريال',
      val1: '۰',
      val2: '۰',
      val3: '۰',
      val4: '۰',
      isImportant: true,
    },
    {
      description: 'سرمايه',
      val1: '۵,۲۰۰,۰۰۰',
      val2: '۳,۲۰۰,۰۰۰',
      val3: '۳,۲۰۰,۰۰۰',
      val4: '',
      isImportant: false,
    },
  ];

  isNegative(data: string): boolean {
    const fnd = data.indexOf('(');
    if (fnd > -1) return true;
    else return false;
  }
}
